messages:
  prefix: "§l§b[AdvancedKits] §r"
  no-permission: "§cLo siento, no tienes permisos para reclamar este kit."
  cooldown: "§c¡Espera! Debes aguardar %time% minutos para volver a usar este kit."
  insufficient-money: "§cNo tienes suficiente dinero. Necesitas $%cost% para obtener este kit."
  kit-received: "§a¡Disfruta! Has recibido el kit %kit%."
  kit-created: "§aEl kit %kit% ha sido creado y guardado en la carpeta /kits."
  kit-updated: "§aEl kit %kit% ha sido actualizado correctamente."
  kit-exists: "§cError: Ya existe un kit con ese nombre. Intenta con otro."
  kit-not-found: "§cEl kit especificado no existe."
  inventory-empty: "§cTu inventario está vacío. Ponte los items que quieres en el kit antes de usar el comando."
  kit-deleted: "§cEl kit %kit% ha sido eliminado permanentemente."
